---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

dependencies:
  galaxy: files/requirements.yml
  python: files/requirements.txt
  system: files/bindep.txt

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest'

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  # Windows Authentication - Kerberos
  - src: files/krb5.conf
    dest: configs
  # Ansible Galaxy
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_base:
    - RUN whoami
    - RUN cat /etc/os-release
    - RUN echo PKGMGR = $PKGMGR, PYCMD = $PYCMD

    # Upgrade pip to use improved dependency resolver
    - RUN $PYCMD -m pip install --upgrade pip

    # Install Red Hat OpenShift client tools by enabling repo (prepare with manual steps below)
    # https://access.redhat.com/solutions/6985157
    # https://docs.openshift.com/container-platform/4.13/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-rpm_cli-developer-commands
    # subscription-manager attach --pool=`subscription-manager list --available --matches '*OpenShift*' | grep "Pool ID" | awk '{print $3}'`
    # subscription-manager repos --list | grep rhocp-4.14
    # (not needed) subscription-manager repos --enable="rhocp-4.12-for-rhel-9-x86_64-rpms"
    - ENV PKGMGR_OPTS "--nodocs --setopt install_weak_deps=0 --enablerepo=rhocp-4.14-for-rhel-9-aarch64-rpms"

    # Install Microsoft azure-cli command line tool (needs dnf to install from url)
    # https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf
    - >
      RUN $PKGMGR install -y dnf &&
      rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
      dnf -y install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm &&
      $PKGMGR -y install azure-cli
    # Install HashiCorp Packer (/usr/bin/packer)
    - >
      RUN curl https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo --output /etc/yum.repos.d/hashicorp.repo &&
      $PKGMGR -y install packer
    # Install Red Hat open-scap command line tool to run security scans on target systems and generate reports
    - RUN $PKGMGR -y install openscap-scanner
  prepend_galaxy:
    # Windows Authentication - Kerberos
    - COPY _build/configs/krb5.conf /etc/krb5.conf
    # Ansible Galaxy
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final:
    # Verify installed packages have compatible dependencies
    # Logged issue https://github.com/ansible/ansible-builder/issues/416
    - RUN pip3 check
    # Clean up
    - >
      RUN $PKGMGR update -y &&
      $PKGMGR clean all &&
      rm -rf /var/cache/{dnf,yum} &&
      rm -rf /var/lib/dnf/history.* &&
      rm -rf /var/log/*
