---
version: 1

build_arg_defaults:
  # ----> Quay Registry
  # Ensure you authorize docker with this registry. 
  # 1. Go to https://quay.io/ and login or create an account
  # 2. Navigate to top-right for Account Settings
  # 3. Select the tool icon on the left
  # 4. Set the Docker CLI Password to enable encrypted passwords
  # 5. Generate the encryped password (re-enter the password)
  # 6. Select the option "Docker Login" to get the CLI command
  # 5. Run the CLI login command to have docker authorized to pull from quay registry
  #EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

  # ----> Red Hat Registry
  # Ensure you perform `docker login` command to authorize with this registry. Go to
  # 1. Go to https://access.redhat.com/terms-based-registry/
  # 2. Create registry service account (if not already created)
  # 3. Drill down on existing service account
  # 4. Select "Docker Login" tab and copy login command and run it locally to authenticate
  # Troubleshooting Authentication Issues with registry.redhat.io
  # https://access.redhat.com/articles/3560571
  # Find existing container images using https://catalog.redhat.com/software/containers/search
  # `minimal` base images contain only ansible-core
  # `supported` base images contain ansible-core and automation content collections supported by Red Hat
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest'

ansible_config: 'ansible.cfg'

dependencies:
  # Ansible dependencies
  # Pull down ansible roles and collections required by your playbooks
  galaxy: requirements-galaxy.yml

  # Python requirements
  # Reference ansible collections to know what python packages you need
  # Only declare python modules that are outside of the `requirements.txt` that
  # already exists in the collection repo. That requirements.txt will be automatically
  # picked up and installed within the image.
  python: requirements-python.txt

  # System binary depenencies
  # For example, ansible collections might require base packages installed
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN echo This is a post-install command!
    # Install azure-cli command line tool
    # - RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc \
    #   && echo "[azure-cli]" > /etc/yum.repos.d/azure-cli.repo \
    #   && echo "name=Azure CLI" >> /etc/yum.repos.d/azure-cli.repo \
    #   && echo "baseurl=https://packages.microsoft.com/yumrepos/azure-cli" >> /etc/yum.repos.d/azure-cli.repo \
    #   && echo "enabled=1" >> /etc/yum.repos.d/azure-cli.repo \
    #   && echo "gpgcheck=1" >> /etc/yum.repos.d/azure-cli.repo \
    #   && echo "gpgkey=https://packages.microsoft.com/keys/microsoft.asc" >> /etc/yum.repos.d/azure-cli.repo \
    #   && dnf -y install azure-cli