---
version: 1

build_arg_defaults:
  # Ignore certifications (verify_ssl=false)
  # ------------------------------>
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: -c

  # Execution Environment Base Image
  # ------------------------------>
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest'

  # Base Builder Image
  # ------------------------------>
  # ansible-builder requires a base builder image in addition to the base image stated above
  #EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8:latest'

ansible_config: ansible.cfg

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    # ANSIBLE-BUILDER PREPEND - START
    RUN whoami
    RUN cat /etc/os-release

    # Windows Authentication - Kerberos
    #COPY krb5.conf /etc/krb5.conf

    # ANSIBLE-BUILDER PREPEND - END
  append: |
    # ANSIBLE-BUILDER APPEND - START

    # Verify installed packages have compatible dependencies
    # Logged issue https://github.com/ansible/ansible-builder/issues/416
    RUN pip3 check

    # Install azure-cli command line tool https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf
    RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
     dnf -y install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm && \
     dnf -y install azure-cli

    # Install packer command line tool to build server images (installs into /usr/bin/packer)
    # Note that `packer` binary already exists in the UBI image but this comes from /usr/sbin/packer and is unrelated!
    RUN curl https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo --output /etc/yum.repos.d/hashicorp.repo && \
     dnf -y install packer

    # Clean up
    RUN dnf update -y \
      && dnf clean all \
      && rm -rf /var/cache/{dnf,yum} \
      && rm -rf /var/lib/dnf/history.* \
      && rm -rf /var/log/*

    # ANSIBLE-BUILDER APPEND - END
