---
# Playbook to test various operations against the newly built Execution Environment image

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure basic operations
      debug: "TODO: Add functional testing here"
      