---
# Ansible Builder Execution Environment
# https://ansible.readthedocs.io/projects/builder/en/latest/definition/#version-3-sample-file

version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest'

dependencies:
  galaxy:
    collections:
      - name: infra.aap_configuration # aap
      - name: ansible.platform # aap
      - name: ansible.hub # aap
      - name: ansible.controller # aap
      #- name: ansible.eda # aap (https://github.com/ansible/event-driven-ansible/issues/424)
  python: files/requirements.txt
  system:
    - dnf
    - jq
    - rsync
    - sudo

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_base:
    - RUN whoami
    - RUN cat /etc/os-release
    - RUN echo PKGMGR = $PKGMGR, PYCMD = $PYCMD
    - RUN $PYCMD -m pip install --upgrade pip
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final:
    - RUN pip3 check # https://github.com/ansible/ansible-builder/issues/416
    - >
      RUN $PKGMGR update -y &&
      $PKGMGR clean all &&
      rm -rf /var/cache/{dnf,yum} &&
      rm -rf /var/lib/dnf/history.* &&
      rm -rf /var/log/*
