#!/bin/bash
set -ex

# Respect existing env if provided by builder
PKGMGR="${PKGMGR:-}"
PKGMGR_OPTS="${PKGMGR_OPTS:-}"
PKGMGR_PRESERVE_CACHE="${PKGMGR_PRESERVE_CACHE:-}"
PYCMD="${PYCMD:=/usr/bin/python3}"
PIPCMD="${PIPCMD:=$PYCMD -m pip}"
PIP_OPTS="${PIP_OPTS-}"

if [ -z "$PKGMGR" ]; then
  PKGMGR=/usr/bin/dnf
  if [ -f "/usr/bin/microdnf" ]; then
    PKGMGR=/usr/bin/microdnf
  fi
fi

if [ "$PKGMGR" = "/usr/bin/microdnf" ] && [ -z "${PKGMGR_OPTS}" ]; then
  PKGMGR_OPTS="--nodocs --setopt install_weak_deps=0"
fi

filter_pkg_list() {
  # Remove packages that are not available or provided via tarball elsewhere
  # Currently filtering: openshift-clients
  sed -E 's/(^| )openshift-clients( |$)/ /g'
}

if [ -f /output/bindep/run.txt ] ; then
  RAW_PACKAGES=$(tr '\n' ' ' < /output/bindep/run.txt)
  PACKAGES=$(echo "$RAW_PACKAGES" | filter_pkg_list | tr -s ' ')
  if [ -n "$PACKAGES" ]; then
    $PKGMGR install -y $PKGMGR_OPTS $PACKAGES || true
  fi
fi

if [ -f /output/bindep/epel.txt ] ; then
  EPEL_PACKAGES=$(tr '\n' ' ' < /output/bindep/epel.txt)
  EPEL_PACKAGES=$(echo "$EPEL_PACKAGES" | filter_pkg_list | tr -s ' ')
  if [ -n "$EPEL_PACKAGES" ]; then
    $PKGMGR install -y $PKGMGR_OPTS --enablerepo epel $EPEL_PACKAGES || true
  fi
fi

if [ -f /output/upper-constraints.txt ] ; then
  CONSTRAINTS="-c /output/upper-constraints.txt"
fi

if [ -f /output/requirements.txt ] ; then
  $PIPCMD install $CONSTRAINTS $PIP_OPTS --cache-dir=/output/wheels -r /output/requirements.txt
fi

EXTRAS=""
for extra in $* ; do
  EXTRAS="${EXTRAS} -r /output/$extra/requirements.txt"
done

if [ -f /output/packages.txt ] ; then
  $PIPCMD install $CONSTRAINTS $PIP_OPTS --cache-dir=/output/wheels -r /output/packages.txt $EXTRAS
else
  if [ $(ls -1 /output/wheels/*whl 2>/dev/null | wc -l) -gt 0 ]; then
    $PIPCMD uninstall -y /output/wheels/*.whl
    $PIPCMD install $CONSTRAINTS $PIP_OPTS --cache-dir=/output/wheels /output/wheels/*.whl $EXTRAS
  elif [ -n "$EXTRAS" ] ; then
    $PIPCMD uninstall -y $EXTRAS
    $PIPCMD install $CONSTRAINTS $PIP_OPTS --cache-dir=/output/wheels $EXTRAS
  fi
fi

if [[ "$PKGMGR_PRESERVE_CACHE" != always ]]; then
  $PKGMGR clean all || true
  rm -rf /var/cache/{dnf,yum}
fi

rm -rf /var/lib/dnf/history.*
rm -rf /var/log/{dnf.*,hawkey.log}

