---
# Dipendenze Ansible
# Scarica i ruoli e le collezioni Ansible necessari per i tuoi playbook
# Visita https://console.redhat.com/ansible/automation-hub per contenuti certificati
# Elenco completo delle collezioni certificate: https://access.redhat.com/articles/3642632

collections:
  # Ansible Automation Platform
  # -------------------------------------------------------------------
  - name: infra.aap_utilities
    version: 2.5.1
  - name: infra.ah_configuration
    version: 2.1.0
  - name: infra.aap_configuration
    version: 3.1.0
  # - name: ansible.scm
  #   version: v1.1.0

  # Piattaforme
  # -------------------------------------------------------------------
  - name: amazon.aws
    version: 9.1.1
  - name: kubernetes.core
    version: 5.1.0
  - name: redhat.openshift
    version: 4.0.1

  # Virtualizzazione
  # -------------------------------------------------------------------
  # oVirt Ansible Collection
  # - name: redhat.rhv
  #   version: 1.4.4

  # OpenStack Ansible Collection
  # - name: openstack.cloud

  # Gestione Server
  # -------------------------------------------------------------------
  - name: community.general
    version: 7.0.0
  #- name: ansible.utils
  #  version: 5.1.2

  # Automazione di Rete
  # -------------------------------------------------------------------
  #- name: ansible.netcommon
  #  version: 5.3.0
  #- name: community.network
  #  version: 5.0.0
  - name: ansible.posix
    version: 2.0.0

