---
# Ansible dependencies
# Pull down ansible roles and collections required by your playbooks
# Navigate to https://console.redhat.com/ansible/automation-hub for certified content
# Complete list of certified collections: https://access.redhat.com/articles/3642632

# Cerified Ansible Collection Content
# https://access.redhat.com/support/articles/ansible-automation-platform-certified-content

collections:
  - name: redhat_cop.aap_utilities # aap
  - name: infra.aap_configuration # aap
  - name: ansible.platform # aap
  - name: ansible.hub # aap
  - name: ansible.controller # aap
  - name: ansible.eda # aap
  - name: amazon.aws # cloud
  - name: azure.azcollection # cloud
  # - name: community.vmware # vmware
  # - name: vmware.vmware_rest # vmware
  #- name: kubernetes.core # containers
  #- name: redhat.openshift # containers
  # https://opendev.org/openstack/ansible-collections-openstack
  # https://storyboard.openstack.org/#!/dashboard/stories
  # Issue with bindep.txt https://storyboard.openstack.org/#!/story/2010889
  # - name: openstack.cloud # openstack
  - name: community.general # general
  - name: ansible.utils # general
  # - name: community.windows # windows
  # - name: ansible.windows # windows
  # - name: ansible.scm # git_publish, git_retrieve modules https://github.com/ansible-collections/ansible.scm
  # - name: ansible.netcommon # networking
  # - name: community.network # networking
  # - name: ansible.posix # networking
  # - name: cisco.asa # networking
  # - name: cisco.ios # networking
  # - name: cisco.iosxr # networking
  # - name: cisco.nxos # networking
  # - name: infoblox.nios_modules # networking
  # - name: f5networks.f5_bigip # networking
  # - name: f5networks.f5_modules # networking
  # - name: paloaltonetworks.panos # networking
  # - name: netbox.netbox # networking
  # - name: ansible.security # security - https://github.com/ansible-collections/ansible.security
  # - name: cloud.common # others; turbo module; cache sharing solution to speed up Ansible modules
