---
# Ansible dependencies
# Pull down ansible roles and collections required by your playbooks
# Navigate to https://console.redhat.com/ansible/automation-hub for certified content
# Complete list of certified collections: https://access.redhat.com/articles/3642632

# Cerified Ansible Collection Content
# https://access.redhat.com/support/articles/ansible-automation-platform-certified-content

collections:
  - name: community.general # general
  - name: ansible.utils # general
  - name: community.windows # windows
  - name: ansible.windows # windows
