# YAML Lint triggered via GitHub Actions
# This file is used to validate YAML files in the repository.
# Since this repository is used for Ansible Execution Environments,
# it is important to ensure that all YAML files are correctly formatted.
# It is not necessary to use the `ansible-lint` tool here.
# https://github.com/marketplace/actions/yamllint-github-action
---
name: 'Yamllint'
on: [push, pull_request]
jobs:
  build:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Perform yamllint
        uses: karancode/yamllint-github-action@master
